### ISSUE TITLE
Multiple ColorPickerTypes in form

### ISSUE THREAD

**Issue by czende** [kunicmarko20/ColorPickerBundle#2]
Hi, there is a bug when I want to use your bundle in form for multiple input types. For the first input type is always triggered color picker and can't dismiss it:
![screen shot 2017-10-23 at 13 14 58](https://user-images.githubusercontent.com/5628485/31886415-795c0a4e-b7f4-11e7-9f50-f636b5f70adb.png)
And in console:
```
Uncaught TypeError: Cannot set property '_left' of undefined
    at HTMLInputElement.h (jqColorPicker.min.js:3)
    at HTMLInputElement.<anonymous> (jqColorPicker.min.js:3)
    at HTMLInputElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLInputElement.q.handle (jquery-3.2.1.min.js:3)
    at Object.trigger (jquery-3.2.1.min.js:4)
    at Object.simulate (jquery-3.2.1.min.js:4)
    at HTMLDocument.c (jquery-3.2.1.min.js:4)
```

**Comment by kunicmarko20** [comment]
This issue here is that I had to load the JS lib and connected it directly to the form type twig. I did not test it with multiple color types in a form, if you have a fix feel free to make a PR if not I will take a closer look when I find some time.

**Comment by kunicmarko20** [comment]
@czende This has been resolved, you can use the master branch if you want, and now you have to add assets at the end of your template and this won't be a problem anymore

**Comment by czende** [comment]
@kunicmarko20 Thank you. Actually I solved it in the same way 😄
